(function(b,d,v){function r(a){for(var b={},c,l,e=0;e<a.length;e++)l=a[e],c=l.r+l.s+l.m,l.c&&(b[c]||(b[c]=[]),b[c].push(a[e]));return b}function n(a){for(var b=1;b<arguments.length;b++){var c=arguments[b];try{if(c.isSupported)return c.send(a)}catch(l){}}}function f(){for(var a=0;a<z.length;a++)z[a]();C.length&&n(r(C.splice(0,C.length)),L,K,F);D=H=0}function q(c,e,m){m=m||{};0===m.bf&&a.isBF||(c={r:m.r||a.rid,s:m.s||b.ue_sid,m:m.m||b.ue_mid,mkt:m.mkt||b.ue_mkt,sn:m.sn||b.ue_sn,c:e,d:c,t:m.t||a.d(),
cs:m.c&&b.ue_qsl},m.b?n(r([c]),L,F):m.nb?n(r([c]),L,K,F):m.img||J[e]?n(r([c]),F):m.ff?(C.push(c),f()):m.n?(C.push(c),0===N?f():D||(D=d.setTimeout(f,N))):(C.push(c),H||(H=d.setTimeout(f,I))))}function t(a,b,c){G++;G==w&&q({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(G<w||c&&c.il)&&q(a,b,c)}function p(){if(!E){for(var a=0;a<g.length;a++)g[a]();for(a=0;a<z.length;a++)z[a]();n(r(C.splice(0,C.length)),L,F);E=!0}}var h={};(function(){function a(b){return 10>
b?"0"+b:b}function b(a){l.lastIndex=0;return l.test(a)?'"'+a.replace(l,function(a){var b=u[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,l){var u,B,h,k,f=e,p,A=l[a];A&&"object"===typeof A&&"function"===typeof A.toJSON&&(A=A.toJSON(a));"function"===typeof g&&(A=g.call(l,a,A));switch(typeof A){case "string":return b(A);case "number":return isFinite(A)?String(A):"null";case "boolean":case "null":return String(A);case "object":if(!A)return"null";
e+=d;p=[];if("[object Array]"===Object.prototype.toString.apply(A)){k=A.length;for(u=0;u<k;u+=1)p[u]=c(u,A)||"null";h=0===p.length?"[]":e?"[\n"+e+p.join(",\n"+e)+"\n"+f+"]":"["+p.join(",")+"]";e=f;return h}if(g&&"object"===typeof g)for(k=g.length,u=0;u<k;u+=1)"string"===typeof g[u]&&(B=g[u],(h=c(B,A))&&p.push(b(B)+(e?": ":":")+h));else for(B in A)Object.prototype.hasOwnProperty.call(A,B)&&(h=c(B,A))&&p.push(b(B)+(e?": ":":")+h);h=0===p.length?"{}":e?"{\n"+e+p.join(",\n"+e)+"\n"+f+"}":"{"+p.join(",")+
"}";e=f;return h}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var l=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e,d,u={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof h.stringify&&(h.stringify=function(a,b,l){var u;d=e="";if("number"===typeof l)for(u=0;u<l;u+=1)d+=" ";else"string"===typeof l&&(d=l);if((g=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})})})();var k=function(){function a(b,c){if(null==b)return c.push("!n");if("number"===typeof b)return c.push("!"+b);if("string"===
typeof b)return"\\"==b[b.length-1]?c.push("'"+b.replace(/'/g,"\\'")+"u005C'"):c.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return c.push(b?"!t":"!f");if(b instanceof Array){c.push("*");for(var l=0;l<b.length;l++)a(b[l],c);return c.push(")")}if("object"==typeof b){c.push("(");for(l in b)b.hasOwnProperty(l)&&(c.push(l),a(b[l],c));return c.push(")")}return c.push("!n")}return{stringify:function(b){var c=[];a(b,c);return c.join("")}}}(),x=b.ue_qsl||2E3,w=1E3,y=function(){},c=d.JSON&&
d.JSON.stringify||h&&h.stringify,e=k.stringify,a=b.ue||{},k=b.uet||y;(b.uet||y)("bb","ue_frst_v2",{wb:1});var M="//"+b.ue_furl+"/1/batch/1/OE/",C=[],g=[],z=[],E=!1,D,H,N=void 0===b.ue_hpfi?1E3:b.ue_hpfi,I=void 0===b.ue_lpfi?1E4:b.ue_lpfi,J={"scheduled-delivery":1},G=0,K=function(){function B(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=y;a.ontimeout=y;a.onprogress=y;a.onload=y;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var b=
0;b<m.length&&!a;b++)try{a=new ActiveXObject(m[b]),m=[m[b]]}catch(c){}return a}}function e(c){for(var m=[],B=c[0]||{},u=0;u<c.length;u++){var d={};d[c[u].c]=c[u].d;m.push(d)}return{rid:B.r||a.rid,sid:B.s||b.ue_sid,mid:B.m||b.ue_mid,mkt:B.mkt||b.ue_mkt,sn:B.sn||b.ue_sn,reqs:m}}var m="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)&&a[b].length){var m=e(a[b]),u=B();
if(!u)throw"";u.open("POST",M,!0);u.setRequestHeader&&u.setRequestHeader("Content-type","text/plain");u.send(c(m))}},buildPOSTBodyLog:e,isSupported:!0}}(),F=function(){return{send:function(B){for(var d in B)if(B.hasOwnProperty(d)){for(var m=B[d],l=m,g={},h=void 0,u=0;u<l.length;u++)h=l[u].c,g[h]||(g[h]=[]),g[h].push(l[u]);var m=m[0]||{},l=m.sn||b.ue_sn,m=M+(m.m||b.ue_mid)+":"+(m.s||b.ue_sid)+":"+(m.r||a.rid)+(l?":"+l:""),l=[],h=m,u=[],R=void 0;for(R in g)if(g.hasOwnProperty(R))for(var O=0;O<g[R].length;O++){var k=
g[R][O],U=encodeURIComponent((k.cs?e:c)(k.d));u.push({l:U,t:k.t,p:1,c:R,d:k.cs?"c":"j"})}g=u;u=void 0;R="$";for(k=0;k<g.length;){O=g[k];u!=O.c?(h+=R+O.c+"=",R="&",u=O.c):h+=",";var U=h,f=O.d+":",p=O,h=(p.l.match(".{1,"+(x-h.length)+"}[^%]{0,2}")||[])[0]||"";p.l=p.l.substr(h.length);h=U+(f+h+":"+O.t);if(O.l)h+=":"+O.p++ +"_",l.push(h),h=m,R="$",u=0;else if(k++,1!=O.p)for(h+=":"+O.p+"_"+O.p,U=0;U<O.p-1;U++)l[l.length-U-1]+=O.p}l.push(h);m=l;for(l=0;l<m.length;l++)(new Image).src=m[l]}},isSupported:!0}}(),
L=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var m=K.buildPOSTBodyLog(a[b]);if(!navigator.sendBeacon(M,c(m)))throw"";}},isSupported:!!navigator.sendBeacon}}();a._fic=F;a._fac=K;a._fbc=L;a._flq=C;a.sid=a.sid||b.ue_sid;a.mid=a.mid||b.ue_mid;a.furl=a.furl||b.ue_furl;a.sn=a.sn||b.ue_sn;a.isBF=function(){var b=d.performance||d.webkitPerformance,c=v.ue_backdetect&&v.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,m=a.bfini;return b&&b.navigation&&2===b.navigation.type||
1<m||!m&&1<c}();try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(P){b.ueLogError(P,{logLevel:"WARN"})}(function(){a.log&&a.log.isStub&&(a.log.replay(function(a,b,c){var l=a[2]||{};l.t=b;l.r=c;l.n=1;t(a[0],a[1],l)}),a.onunload.replay(function(a){g.push(a[0])}),a.onflush.replay(function(a){z.push(a[0])}))})();a.log=t;a.log.reset=function(){G=0};a.onunload=function(a){g.push(a)};a.onflush=function(a){z.push(a)};
a.attach("beforeunload",p);a.attach("pagehide",p);k("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(b,d){function v(b){if(b)return b.replace(/^\s+|\s+$/g,"")}function r(c,e){if(!c)return{};c.m&&c.m.message&&(c=c.m);var a=e.m||e.message||"",a=c.m&&c.m.message?a+c.m.message:c.m&&c.m.target&&c.m.target.tagName?a+("Error handler invoked by "+c.m.target.tagName+" tag"):c.m?a+c.m:c.message?a+c.message:a+"Unknown error",a={m:a,f:c.f||c.sourceURL||c.fileName||c.filename||c.m&&c.m.target&&c.m.target.src,l:c.l||c.line||c.lineno||c.lineNumber,c:c.c?""+c.c:c.c,s:[],t:b.ue.d(),name:c.name,type:c.type,
csm:h+" "+(c.fromOnError?"onerror":"ueLogError")},d,f,g=0,q=0,r;d=c.stack||(c.err?c.err.stack:"");a.pageURL=e.pageURL||""+(window.location?window.location.href:"")||"missing";a.logLevel=e.logLevel||p;if(f=e.attribution)a.attribution=""+f;if(d&&d.split)for(a.csm+=" stack",f=d.split("\n");g<f.length&&a.s.length<k;)(d=f[g++])&&a.s.push(v(d));else for(a.csm+=" callee",f=n(c.args||arguments,"callee"),q=g=0;f&&g<k;)r=x,f.skipTrace||(d=f.toString())&&d.substr&&(r=0===q?4*x:r,r=1==q?2*x:r,a.s.push(d.substr(0,
r)),q++),f=n(f,"caller"),g++;if(!a.f&&0<a.s.length&&(g=a)&&g.s){var t;d=0<g.s.length?g.s[0]:"";f=1<g.s.length?g.s[1]:"";d&&(t=d.match(y));t&&3==t.length||!f||(t=f.match(w));t&&3==t.length&&(g.f=t[1],g.l=t[2])}return a}function n(b,e){try{return b[e]}catch(a){}}function f(c,e){if(c){var a=r(c,e);b.ue.log(a,e.channel||t,{nb:1});try{if(!c.fromOnError){var h=d.console,k=d.JSON,g="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(h){if(k&&k.stringify)try{g+=
k.stringify(a)}catch(f){g+="no info provided; converting to string failed"}else g+=a.m;"function"===typeof h.error?h.error(g,a):"function"===typeof h.log&&h.log(g,a)}}}catch(p){}}}function q(c,e){if(c&&!(b.ue_err.ec>b.ue_err.mxe)){b.ue_err.ec++;b.ue_err.ter.push(c);e=e||{};var a=c.logLevel||e.logLevel;e.logLevel=a;e.attribution=c.attribution||e.attribution;a&&a!=p||ue_err.ecf++;f(c,e)}}if(!b.ueLogError||b.ueLogError.isStub){var t=b.ue_err_chan||"jserr",p="FATAL",h="v5",k=20,x=256,w=/\(?([^\s]*):(\d+):\d+\)?/,
y=/.*@(.*):(\d*)/;f.skipTrace=1;r.skipTrace=1;q.skipTrace=1;(function(){if(b.ue_err.erl){var c=b.ue_err.erl.length,e,a;for(e=0;e<c;e++)a=b.ue_err.erl[e],f(a.ex,a.info);ue_err.erl=[]}})();b.ueLogError=q}})(ue_csm,window);
(function(b,d){b.ue_cel||(b.ue_cel=function(){function v(b,e){e?e.r=w:e={r:w,c:1};e.clog&&h.clog?h.clog(b,e.ns||t,e):e.glog&&h.glog?h.glog(b,e.ns||t,e):h.log(b,e.ns||t,e)}function r(){var b=f.length;if(0<b){for(var e=[],a=0;a<b;a++){var d=f[a].api;d.ready()?(d.on({ts:h.d,ns:t}),q.push(f[a]),v({k:"mso",n:f[a].name,t:h.d()})):e.push(f[a])}f=e}}function n(){if(!n.executed){for(var b=0;b<q.length;b++)q[b].api.off&&q[b].api.off({ts:h.d,ns:t});v({k:"eod",t0:h.t0,t:h.d()},{c:1,il:1});n.executed=1;for(b=
0;b<q.length;b++)f.push(q[b]);q=[];clearTimeout(p)}}var f=[],q=[],t=b.ue_cel_ns||"cel",p,h=b.ue,k=b.uet,x=b.uex,w=h.rid,y=d.requestAnimationFrame||function(b){b()};if(h.isBF)v({k:"bft",t:h.d()});else return"function"==typeof k&&k("bb","csmCELLSframework",{wb:1}),setTimeout(r,0),h.onunload(n),p=setTimeout(n,6E5),"function"==typeof x&&x("ld","csmCELLSframework",{wb:1}),{registerModule:function(b,e){f.push({name:b,api:e});v({k:"mrg",n:b,t:h.d()});r()},reset:function(b){v({k:"rst",t0:h.t0,t:h.d()});f=
f.concat(q);q=[];for(var e=f.length,a=0;a<e;a++)f[a].api.off(),f[a].api.reset();w=b||h.rid;r();clearTimeout(p);p=setTimeout(n,6E5);n.executed=0},timeout:function(b,e){return d.setTimeout(function(){y(b)},e)},log:v}}())})(ue_csm,window);
(function(b,d,v){b.ue_pdm||ue.isBF||(b.ue_pdm=function(){function r(){var a={w:q.width,aw:q.availWidth,h:q.height,ah:q.availHeight,cd:q.colorDepth,pd:q.pixelDepth},c={w:(v.body||{}).scrollWidth,h:(v.body||{}).scrollHeight};k&&k.w==a.w&&k.h==a.h&&k.aw==a.aw&&k.ah==a.ah&&k.pd==a.pd&&k.cd==a.cd||(k=a,k.t=p(),k.k="sci",y(k));x&&x.w==c.w&&x.h==c.h||(x=c,x.t=p(),x.k="doi",y(x));t=b.ue_cel.timeout(r,h)}function n(){y({k:"ebl",t:p()},{ff:1})}function f(){y({k:"efo",t:p()})}var q,t,p,h,k,x,w=b.ue,y=b.ue_cel.log,
c=b.uet,e=b.uex;"function"==typeof c&&c("bb","csmCELLSpdm",{wb:1});return{on:function(a){h=a.timespan||500;p=a.ts;q=d.screen;w.attach&&(w.attach("blur",n,d),w.attach("focus",f,d));a=d.location;y({k:"pmd",o:a.origin,p:a.pathname,t:p()});b.ue_cel.timeout(r,0);"function"==typeof e&&e("ld","csmCELLSpdm",{wb:1})},off:function(a){clearTimeout(t);w.detach&&(w.detach("blur",n,d),w.detach("focus",f,d));w.count&&(w.count("cel.PDM.TotalExecutions",0),w.count("cel.PDM.TotalExecutionTime",0),w.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return v.body&&b.ue_cel&&b.ue_cel.log},reset:function(){k=x=null}}}(),b.ue_cel&&b.ue_cel.registerModule("page module",b.ue_pdm))})(ue_csm,window,document);
(function(b,d){b.ue_vpm||ue.isBF||(b.ue_vpm=function(){function v(){var a=t(),b={w:d.innerWidth,h:d.innerHeight,x:d.pageXOffset,y:d.pageYOffset};n&&n.w==b.w&&n.h==b.h&&n.x==b.x&&n.y==b.y||(b.t=a,b.k="vpi",n=b,x(n,{clog:1}));f=0;p=t()-a;h+=1}function r(){f||(f=b.ue_cel.timeout(v,q))}var n,f,q,t,p=0,h=0,k=b.ue,x=b.ue_cel.log,w=b.uet,y=b.uex,c=k.attach,e=k.detach;"function"==typeof w&&w("bb","csmCELLSvpm",{wb:1});return{on:function(a){t=a.ts;q=a.timespan||100;b.ue_cel.timeout(v,0);c&&(c("scroll",r),
c("resize",r));"function"==typeof y&&y("ld","csmCELLSvpm",{wb:1})},off:function(a){clearTimeout(f);e&&(e("scroll",r),e("resize",r));k.count&&(k.count("cel.VPI.TotalExecutions",h),k.count("cel.VPI.TotalExecutionTime",p),k.count("cel.VPI.AverageExecutionTime",p/h))},ready:function(){return b.ue_cel&&b.ue_cel.log},reset:function(){n=void 0},getVpi:function(){return n}}}(),b.ue_cel&&b.ue_cel.registerModule("viewport module",b.ue_vpm))})(ue_csm,window);
(function(b,d,v){var r=b.ue||{};!r.isBF&&!b.ue_fem&&v.querySelector&&d.getComputedStyle&&[].forEach&&(b.ue_fem=function(){function n(a,b){return a>b?3>a-b:3>b-a}function f(a,b,c){var l;a:{try{if(a){var m=a.getBoundingClientRect();l={x:m.left+c.x|0,y:m.top+c.y|0,w:m.width|0,h:m.height|0,d:(0===a.offsetWidth&&0===a.offsetHeight)|0}}else l=void 0;break a}catch(B){}l=void 0}if(l&&!a.cel_b)a.cel_b=l,C({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi",cl:a.className},{clog:1});
else{if(c=l)c=a.cel_b,m=l,c=m.d===c.d&&1===m.d?!1:!(n(c.x,m.x)&&n(c.y,m.y)&&n(c.w,m.w)&&n(c.h,m.h)&&c.d===m.d);c&&(a.cel_b=l,C({n:a.cel_n,w:a.cel_b.w,h:a.cel_b.h,d:a.cel_b.d,x:a.cel_b.x,y:a.cel_b.y,t:b,k:"ewi"},{clog:1}))}}function q(a,b,c){var l;l=a.c?v.getElementsByClassName(a.c):a.id?[v.getElementById(a.id)]:v.querySelectorAll(a.s);a.w=[];for(widgetIndex=0;widgetIndex<l.length;widgetIndex++){var B=l[widgetIndex];B&&(B.cel_n||(B.cel_n=B.getAttribute("cel_widget_id")||(a.id_gen||M)(B,widgetIndex)||
B.id),a.w.push(B),h(m,B,b,c))}}function t(a,b){g.contains(a)||C({n:a.cel_n,t:b,k:"ewd"},{clog:1})}function p(a){F.length&&ue_cel.timeout(function(){for(var b=T(),m=!1;T()-b<c&&!m;){for(m=P;0<m--&&0<F.length;){var B=F.shift();l[B.type](B.elem,B.time,B.pageOffset)}m=0===F.length}L++;p(a)},0)}function h(a,b,c,l){F.push({type:a,elem:b,time:c,pageOffset:l})}function k(b,c,l){for(var m=0;m<a.length;m++)for(var B=a[m].w||[],e=0;e<B.length;e++)h(b,B[e],c,l)}function x(){K||(K=b.ue_cel.timeout(function(){K=
null;var b={x:d.pageXOffset,y:d.pageYOffset},c=e();k(B,c);for(var l=0;l<a.length;l++)h(Q,a[l],c,b);p(c)},y))}function w(){K||G||(G=b.ue_cel.timeout(function(){G=null;var a={x:d.pageXOffset,y:d.pageYOffset},b=e();k(m,b,a);p(b)},y))}var y=50,c=4.5,e,a=[],M=function(){},C=b.ue_cel.log,g,z,E,D,H=d.MutationObserver||d.WebKitMutationObserver||d.MozMutationObserver,N=!!H,I,J,G,K,F=[],L=0,P=null,B="removedWidget",Q="updateWidgets",m="processWidget",l,S=d.performance||{},T=S.now&&function(){return S.now()}||
function(){return Date.now()};"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(c){function m(){if(E&&D&&g&&g.contains&&g.getBoundingClientRect&&e){l={removedWidget:t,updateWidgets:q,processWidget:f};if(N){var a={attributes:!0,subtree:!0};I=new H(w);J=new H(x);I.observe(g,a);J.observe(g,{childList:!0,subtree:!0});J.observe(z,a)}else E.call(g,"DOMAttrModified",w),E.call(g,"DOMNodeInserted",x),E.call(g,"DOMNodeRemoved",x),E.call(z,"DOMNodeInserted",w),E.call(z,"DOMNodeRemoved",
w);x()}}g=v.body;z=v.head;E=g.addEventListener;D=g.removeEventListener;e=c.ts;a=b.cel_widgets||[];P=c.bs||5;r.deffered?m():r.attach&&r.attach("load",m);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){E&&D&&g&&g.contains&&g.getBoundingClientRect&&e&&(J&&(J.disconnect(),J=null),I&&(I.disconnect(),I=null),D.call(g,"DOMAttrModified",w),D.call(g,"DOMNodeInserted",x),D.call(g,"DOMNodeRemoved",x),D.call(z,"DOMNodeInserted",w),D.call(z,"DOMNodeRemoved",w));r.count&&r.count("cel.widgets.batchesProcessed",
L)},ready:function(){return b.ue_cel&&b.ue_cel.log},reset:function(){a=b.cel_widgets||[]}}}(),b.ue_cel&&b.ue_fem&&b.ue_cel.registerModule("features module",b.ue_fem))})(ue_csm,window,document);